// <auto-generated />
namespace Violin.Store.Database.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class InitCreate_MySQL : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitCreate_MySQL));
        
        string IMigrationMetadata.Id
        {
            get { return "201704090546331_InitCreate_MySQL"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
